version: "3.8"

services:
  posts-db:
    image: postgres
    container_name: posts-db
    environment:
      - POSTGRES_DB=postsDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - linkedin-network
    volumes:
      - posts-db-data:/var/lib/postgresql/data

  user-db:
    image: postgres
    container_name: user-db
    environment:
      - POSTGRES_DB=userDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - linkedin-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

  posts-service:
    image: tusaryan/linkedin-app/posts-service
    container_name: posts-service
    networks:
      - linkedin-network
    depends_on:
      - posts-db

  user-service:
    image: tusaryan/linkedin-app/user-service
    container_name: user-service
    networks:
      - linkedin-network
    depends_on:
      - user-db

networks:
  linkedin-network:

volumes:
  posts-db-data:
  user-db-data:
