spring.application.name: api-gateway

server.port: 8080
#eureka.client.service-url.defaultZone: http://discovery-server:8761/eureka

jwt.secretKey: asdfladf98a7df89aysf8d9yasiudfha9s87dfa89syudhfa98sdfyaisuhdfa98sfy

#api gateway config
spring:
  cloud:
    gateway:
#      defining multiple routes
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URI:lb://USER-SERVICE}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: posts-service
          uri: ${POSTS_SERVICE_URI:lb://POSTS-SERVICE}
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: connections-service
          uri: ${CONNECTIONS_SERVICE_URI:lb://CONNECTIONS-SERVICE}
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
